### ISSUE TITLE
CI/CD integration

### ISSUE THREAD

**Issue by webcat12345** [PDFTron/webviewer-angular-sample#4]
Good sample to learn a lot. It works fine on local but when we are setting up CI/CD env, it throws error.

We are using CircleCI and here are details.

```
6%Downloading WebViewer... 84.6%Downloading WebViewer... 100%
Download completed.

Extracting WebViewer...Error: ENOENT: no such file or directory, stat '/home/circleci/repo/src/lib/WebViewer/lib'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

After some investigation, we are seeing this part.

`node_modules/@pdftron/webviewer-downloader/download-webviewer.js`

line - 37.

```
decompress(path.resolve(location, './WebViewer.zip'), location).then(() => {
          fs.copySync(path.resolve(location, './WebViewer/lib'), path.resolve(location));
          fs.removeSync(path.resolve(location, './WebViewer'));

          fs.removeSync(path.resolve(location, './ui-legacy'));
          fs.removeSync(path.resolve(location, './package.json'));
          fs.removeSync(path.resolve(location, './webviewer.js'));

          // delete .min.js if we're using the NPM arcitecture (this is included in the package)
          if (options.npm) {
            fs.removeSync(path.resolve(location, './webviewer.min.js'));
          }

          if (options.coreOnly) {
            fs.removeSync(path.resolve(location, './webviewer.min.js'));
            fs.removeSync(path.resolve(location, './ui'));
          } else {
            fs.moveSync(path.resolve(location, './ui/build'), path.resolve(location, './temp'));
            fs.removeSync(path.resolve(location, './ui'))
            fs.moveSync(path.resolve(location, './temp'), path.resolve(location, './ui/build'))
          }

          fs.removeSync(path.resolve(location, './WebViewer.zip'));

          process.stdout.clearLine();
          process.stdout.cursorTo(0);
          process.stdout.write(`${CYAN}Extracting WebViewer... 100%${CYAN}\n${GREEN}Extract completed.${RESET}\n\n\n`);

          if (options.npm) {
            console.log(`\n${GREEN}WebViewer successfully installed! You now need to copy the static files required to use WebViewer into your ${MAGENTA}build/dist${GREEN} folder. See ${CYAN}http://r.pdftron.com/npm${GREEN} for more details.${RESET}\n`);
          }

          r();
        }).catch((err) => {
          console.log(`${RED}${err}${RESET}`);
        });
```

I am not sure if decompression is failed or my CircleCI config is wrong.

```
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: npm install
```

`working_directory` segment here goes.

Thank you!
